// // -------------------------------Start: 40_4 ---------------------------------------
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//       {/* (3) then in Navbar.jsx file */}
//       <Navbar/>
//         {children}
//       </body>
//     </html>
//   );
// }
// // ---------------------End:40_4-(1) to (13) --------------------------------
// -------------------------------Start: 40_9 ---------------------------------------
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// // (4)st
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// // (4)en

// (5)st commit (4)
export const metadata = {
  title: "My Users and Blogs App",
  description: "Generated by create next app",
};
// (5)en then create not-found.jsx file in app folder 



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
// ---------------------End:40_9-(1) to (13) --------------------------------
